# Generated by Django 5.2 on 2025-04-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctor_management.doctorprofile'),
        ),
    ]
